Repository CATcher-org/WATcher, pull requests merged in 2023-07, with the labels that each got.

#149 Disable milestone filter if there are no milestones
  src/app/core/services/milestone.service.ts
  src/app/shared/filter-bar/filter-bar.component.html
Labels: s.toMerge

#141 Update website title after changing repository
  src/app/shared/layout/header.component.ts
Labels: s.toMerge

#147 Add wrap for username in issues-viewer's card-view
  src/app/issues-viewer/card-view/card-view.component.css
Labels: s.toMerge

#131 Detail page detail list
  src/app/shared/issue-tables/IssueList.ts
  src/app/user-detail-viewer/profile-list/profile-list.component.css
  src/app/user-detail-viewer/profile-list/profile-list.component.html
  src/app/user-detail-viewer/profile-list/profile-list.component.ts
  src/app/user-detail-viewer/user-detail-viewer.component.html
  src/app/user-detail-viewer/user-detail-viewer.component.ts
  src/app/user-detail-viewer/user-detail-viewer.module.ts
Labels: category.Feature

#132 Detail page commit list
  graphql/fragments/commit-stats.fragment.graphql
  graphql/queries/fetch-activity.graphql
  src/app/app.module.ts
  src/app/core/models/github/github-commit.model.ts
  src/app/core/models/github/github-graphql.commitstats.model.ts
  src/app/core/services/github.service.ts
  src/app/user-detail-viewer/commit-list/commit-list.component.css
  src/app/user-detail-viewer/commit-list/commit-list.component.html
  src/app/user-detail-viewer/commit-list/commit-list.component.ts
  src/app/user-detail-viewer/datetimehelper.ts
  src/app/user-detail-viewer/profile-details/profile-details.component.css
  src/app/user-detail-viewer/profile-details/profile-details.component.html
  src/app/user-detail-viewer/profile-details/profile-details.component.ts
  src/app/user-detail-viewer/user-detail-viewer.component.html
  src/app/user-detail-viewer/user-detail-viewer.component.ts
  src/app/user-detail-viewer/user-detail-viewer.module.ts
Labels: category.Feature

#158 Add link to documentation in Readme
  README.md
Labels: s.toMerge

#157 Update PR template
  .github/pull_request_template.md
Labels: s.toMerge

#159 Autofill repository URL with Browser Cache
  src/app/auth/session-selection/session-selection.component.html
  src/app/auth/session-selection/session-selection.component.ts
  src/app/core/services/phase.service.ts
  src/app/shared/repo-change-form/repo-change-form.component.html
  src/app/shared/repo-change-form/repo-change-form.component.ts
Labels: s.toMerge

#143 [#72] Remove code related to creating and updating repos
  graphql/queries/fetch-issues-by-team.graphql
  src/app/core/services/github.service.ts
  src/app/core/services/issue.service.ts
  src/app/core/services/repo-creator.service.ts
  src/app/core/services/upload.service.ts
  tests/services/repo-creator.service.spec.ts
  tests/services/upload.service.spec.ts
Labels: s.toMerge

#162 Extract method from header.component into phase.service.ts
  src/app/core/services/phase.service.ts
  src/app/shared/layout/header.component.ts
Labels: s.toMerge

#145 [#72] Remove package ngx-markdown
  angular.json
  package.json
  src/app/app.module.ts
  src/app/issues-viewer/issues-viewer.module.ts
  src/app/shared/lib/marked.ts
  src/markdown.css
  tests/app/shared/lib/marked.spec.ts
Labels: s.toMerge

#133 Detail page commit list diffstat
  src/app/core/models/cumulative-stats.model.ts
  src/app/core/models/datastructure/rsq.model.ts
  src/app/user-detail-viewer/commit-list/commit-list.component.html
  src/app/user-detail-viewer/commit-list/commit-list.component.ts
  src/app/user-detail-viewer/diffstat/diffstat.component.css
  src/app/user-detail-viewer/diffstat/diffstat.component.html
  src/app/user-detail-viewer/diffstat/diffstat.component.ts
  src/app/user-detail-viewer/user-detail-viewer.module.ts
Labels: s.toMerge, category.Enhancement

#146 [#72] Remove unused code from catcher models
  package.json
  src/app/auth/session-selection/session-selection.component.html
  src/app/auth/session-selection/session-selection.component.ts
  src/app/core/models/assignee.model.ts
  src/app/core/models/checkbox.model.ts
  src/app/core/models/conflict/addition.model.ts
  src/app/core/models/conflict/changes.model.ts
  src/app/core/models/conflict/conflict.model.ts
  src/app/core/models/conflict/no-change.model.ts
  src/app/core/models/conflict/removal.model.ts
  src/app/core/models/generators/github-issue.generator.ts
  src/app/core/models/github/github-issue.model.ts
  src/app/core/models/issue-dispute.model.ts
  src/app/core/models/issue.model.ts
  src/app/core/models/parser/admins.model.ts
  src/app/core/models/parser/parsed-user-data.model.ts
  src/app/core/models/parser/roles.model.ts
  src/app/core/models/parser/students.model.ts
  src/app/core/models/parser/tabulated-user-data.model.ts
  src/app/core/models/parser/teams.model.ts
  src/app/core/models/parser/tutors.model.ts
  src/app/core/models/templates/sections/common-parsers.model.ts
  src/app/core/models/templates/sections/duplicate-of-section.model.ts
  src/app/core/models/templates/sections/issue-dispute-section-parser.model.ts
  src/app/core/models/templates/sections/issue-dispute-section.model.ts
  src/app/core/models/templates/sections/moderation-section-parser.model.ts
  src/app/core/models/templates/sections/moderation-section.model.ts
  src/app/core/models/templates/sections/section.model.ts
  src/app/core/models/templates/sections/tester-response-section-parser.model.ts
  src/app/core/models/templates/sections/tester-response-section.model.ts
  src/app/core/models/templates/team-accepted-template.model.ts
  src/app/core/models/templates/team-response-template.model.ts
  src/app/core/models/templates/template.model.ts
  src/app/core/models/templates/tester-response-template.model.ts
  src/app/core/models/templates/tutor-moderation-issue-template.model.ts
  src/app/core/models/templates/tutor-moderation-todo-template.model.ts
  src/app/core/models/tester-response.model.ts
  src/app/core/models/timeline-item.model.ts
  src/app/core/services/issue.service.ts
  src/app/issues-viewer/card-view/card-view.component.css
  src/app/issues-viewer/issues-viewer.component.html
  src/app/shared/issue-tables/IssuesDataTable.ts
  src/app/shared/issue-tables/issue-sorter.ts
  src/app/shared/layout/header.component.ts
  src/app/shared/repo-change-form/repo-change-form.component.html
  src/app/shared/repo-change-form/repo-change-form.component.ts
  tests/model/checkbox.model.spec.ts
  tests/model/templates/sections/issue-dispute-section-parser.model.spec.ts
  tests/model/templates/sections/moderation-section-parser.model.spec.ts
  tests/model/templates/sections/tester-response-section-parser.model.spec.ts
  tests/model/templates/team-accepted-template.model.spec.ts
  tests/model/templates/team-response-template.model.spec.ts
  tests/model/templates/tester-response-template.model.spec.ts
  tests/model/templates/tutor-moderation-issue-template.model.spec.ts
  tests/model/templates/tutor-moderation-todo-template.model.spec.ts
Labels: s.toMerge

#173 Fix hover, click interaction with issue cards
  src/app/issues-viewer/card-view/card-view.component.css
  src/app/issues-viewer/card-view/card-view.component.html
Labels: s.toMerge

#134 Detail page commit list calendar range selection
  package.json
  src/app/user-detail-viewer/commit-list/commit-list.component.html
  src/app/user-detail-viewer/commit-list/commit-list.component.ts
  src/app/user-detail-viewer/query-range/query-range.component.ts
  src/app/user-detail-viewer/query-range/queryrange.html
  src/app/user-detail-viewer/user-detail-viewer.module.ts
Labels: s.toReview, category.Enhancement, category.Feature

#170 Reduce code duplication in repository url suggestions
  src/app/auth/session-selection/session-selection.component.ts
  src/app/core/services/phase.service.ts
  src/app/core/services/repo-url-cache.service.ts
  src/app/shared/repo-change-form/repo-change-form.component.ts
  tests/services/repo-url-cache.service.spec.ts
Labels: s.toMerge, s.Conflict

#175 Fix ng test type error
  src/typings.d.ts
Labels: s.toReview

#177 Allow keyboard enter when changing repository
  src/app/shared/repo-change-form/repo-change-form.component.html
Labels: s.toMerge

#150 Add reset labels feature
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.html
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.ts
Labels: s.toReview

#163 Change labels filter to dynamic height, fixed width, and shadow scroll bar
  src/app/core/services/phase.service.ts
  src/app/core/services/repo-url-cache.service.ts
  src/app/issues-viewer/card-view/card-view.component.css
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.css
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.html
  src/app/shared/repo-change-form/repo-change-form.component.html
Labels: s.toMerge

#182 Filter for 'Merged'
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/issue-tables/dropdownfilter.ts
Labels: s.toReview
