Repository CATcher-org/WATcher, pull requests merged in 2023-03, with the labels that each got.

#82 Add show and hide labels menu
  src/app/core/services/github.service.ts
  src/app/issues-viewer/card-view/card-view.component.html
  src/app/issues-viewer/issues-viewer.component.css
  src/app/issues-viewer/issues-viewer.component.html
  src/app/issues-viewer/issues-viewer.component.ts
  src/app/issues-viewer/issues-viewer.module.ts
  src/app/issues-viewer/label-chip-bar/label-chip-bar.component.css
  src/app/issues-viewer/label-chip-bar/label-chip-bar.component.html
  src/app/issues-viewer/label-chip-bar/label-chip-bar.component.ts
  src/app/issues-viewer/label-filter-bar/label-filter-bar.component.css
  src/app/issues-viewer/label-filter-bar/label-filter-bar.component.html
  src/app/issues-viewer/label-filter-bar/label-filter-bar.component.ts
  src/app/issues-viewer/label-filter-bar/label-filter-bar.module.ts
  src/app/shared/issue-tables/IssuesDataTable.ts
  tests/app/issues-viewer/label-filter-bar/label-filter-bar.component.spec.ts
Labels: category.Feature

#89 Fix wrong octicon displayed for closed PR
  src/app/issues-viewer/card-view/card-view.component.css
  src/app/issues-viewer/card-view/card-view.component.ts
Labels: s.toReview, category.Bug

#92 Remove label-filter-bar as module export
  src/app/issues-viewer/label-filter-bar/label-filter-bar.module.ts
Labels: s.toMerge

#95 Merge main into release for v0.1.0
  package.json
  src/app/issues-viewer/label-filter-bar/label-filter-bar.module.ts
Labels: s.OnHold

#97 Improve UIX for milestones and label-filter-bar
  src/app/core/models/issue.model.ts
  src/app/core/models/milestone.model.ts
  src/app/core/services/milestone.service.ts
  src/app/issues-viewer/card-view/card-view.component.html
  src/app/issues-viewer/issues-viewer.component.html
  src/app/issues-viewer/issues-viewer.component.ts
  src/app/issues-viewer/label-filter-bar/label-filter-bar.component.css
  src/app/issues-viewer/label-filter-bar/label-filter-bar.component.html
  src/app/shared/issue-tables/IssuesDataTable.ts
Labels: aspect-UIX
