Repository CATcher-org/WATcher, pull requests merged in 2024-03, with the labels that each got.

#257 Refactor test cases for Issue Model
  tests/constants/githubissue.constants.ts
  tests/model/issue.model.spec.ts
Labels: s.toReview

#263 Refactor test cases for Phase Service
  tests/constants/session.constants.ts
  tests/services/phase.service.spec.ts
Labels: s.toReview

#272 Automatic deployment
  .github/workflows/deployment-actions.yml
Labels: aspect-Process

#265 Refactor title filter
  src/app/core/services/filters.service.ts
  src/app/issues-viewer/card-view/card-view.component.html
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/issue-pr-card/issue-pr-card.component.html
  src/app/shared/issue-pr-card/issue-pr-card.component.ts
  src/app/shared/issue-tables/IssuesDataTable.ts
  src/app/shared/issue-tables/dropdownfilter.ts
  src/app/shared/issue-tables/filterableTypes.ts
Labels: aspect-CodeQuality

#289 Refactor milestones to save by name
  src/app/core/models/milestone.model.ts
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/issue-tables/dropdownfilter.ts
Labels: aspect-CodeQuality

#292 Deploy v1.1.1
  package.json
  src/app/core/models/milestone.model.ts
  src/app/core/services/filters.service.ts
  src/app/issues-viewer/card-view/card-view.component.html
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/issue-pr-card/issue-pr-card.component.html
  src/app/shared/issue-pr-card/issue-pr-card.component.ts
  src/app/shared/issue-tables/IssuesDataTable.ts
  src/app/shared/issue-tables/dropdownfilter.ts
  src/app/shared/issue-tables/filterableTypes.ts
  src/app/shared/issue-tables/issue-sorter.ts
  src/test.ts
  tests/app/issues-viewer/label-filter-bar/label-filter-bar.component.spec.ts
  tests/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.spec.ts
  tests/app/shared/issue-tables/issue-sorter.spec.ts
  tests/constants/label.constants.ts
  tests/services/phase.service.spec.ts
  tests/services/user.service.spec.ts
Labels: release

#285 Release changelog automation
  .github/release-drafter.yml
Labels: aspect-Process

#281 Keep filters when switching repos
  src/app/core/models/repo-change-response.model.ts
  src/app/core/services/filters.service.ts
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.html
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.ts
  src/app/shared/layout/header.component.ts
  src/app/shared/repo-change-form/repo-change-form.component.css
  src/app/shared/repo-change-form/repo-change-form.component.html
  src/app/shared/repo-change-form/repo-change-form.component.ts
  tests/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.spec.ts
Labels: category.Enhancement, category.Feature

#311 Keep milestones when switching repo
  src/app/core/services/filters.service.ts
  src/app/shared/filter-bar/filter-bar.component.ts
Labels: category.Enhancement

#314 Add filters to url
  src/app/core/services/filters.service.ts
  src/app/core/services/label.service.ts
  src/app/issues-viewer/issues-viewer.component.ts
  src/app/shared/layout/header.component.ts
Labels: category.Enhancement

#327 Create release 1.2.0
  package.json
Labels: release
