Repository CATcher-org/WATcher, pull requests merged in 2024-02, with the labels that each got.

#233 Improve activity dashboard design
  src/app/activity-dashboard/activity-dashboard.component.css
  src/app/activity-dashboard/activity-dashboard.component.html
  src/app/activity-dashboard/activity-dashboard.component.ts
  src/app/activity-dashboard/activity-dashboard.module.ts
  src/app/activity-dashboard/event-tables/event-tables.component.css
  src/app/activity-dashboard/event-tables/event-tables.component.html
  src/app/activity-dashboard/event-tables/event-tables.component.ts
  src/app/activity-dashboard/event-tables/no-events-error.model.ts
  src/app/activity-dashboard/event-week-details/event-week-details.component.css
  src/app/activity-dashboard/event-week-details/event-week-details.component.html
  src/app/activity-dashboard/event-week-details/event-week-details.component.ts
Labels: s.toReview

#238 Remove unused services
  src/app/core/services/data.service.ts
  src/app/core/services/permission.service.ts
Labels: aspect-CodeQuality

#243 Remove markdown.css from test env stylesheets
  angular.json
Labels: s.toMerge

#253 Remove unused models
  src/app/core/models/comment.model.ts
  src/app/core/models/data-file.model.ts
  src/app/core/models/team.model.ts
  src/app/core/models/user.model.ts
Labels: aspect-CodeQuality

#250 Remove unused session-fix-confirmation component
  src/app/app.module.ts
  src/app/core/services/session-fix-confirmation/session-fix-confirmation.component.css
  src/app/core/services/session-fix-confirmation/session-fix-confirmation.component.html
  src/app/core/services/session-fix-confirmation/session-fix-confirmation.component.ts
Labels: aspect-CodeQuality

#259 Refactor certain filters into its own service
  src/app/core/services/filters.service.ts
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.ts
  src/app/shared/layout/header.component.ts
Labels: aspect-CodeQuality

#260 Remove test cases for permissions service
  tests/services/permissions.service.spec.ts
Labels: s.toReview

#262 Remove constants for DataFile and Team model
  tests/constants/data.constants.ts
Labels: s.toReview

#258 Refactor test cases for Label Service
  tests/constants/label.constants.ts
  tests/services/label.service.spec.ts
Labels: s.toReview

#261 Refactor sorting
  src/app/issues-viewer/card-view/card-view.component.ts
  src/app/issues-viewer/issues-viewer.component.html
  src/app/shared/filter-bar/filter-bar.component.html
  src/app/shared/filter-bar/filter-bar.component.ts
  src/app/shared/filter-bar/label-filter-bar/label-filter-bar.component.ts
  src/app/shared/issue-tables/IssuesDataTable.ts
  src/app/shared/issue-tables/dropdownfilter.ts
  src/app/shared/issue-tables/issue-sorter.ts
Labels: aspect-CodeQuality

#264 Refactor milestone filters
  src/app/shared/filter-bar/filter-bar.component.html
Labels: aspect-CodeQuality
